export const GET_EXCHANGE_RATES_REQUEST = "GET_EXCHANGE_RATES_REQUEST";
export const GET_EXCHANGE_RATES_SUCCESS = "GET_EXCHANGE_RATES_SUCCESS";
export const GET_EXCHANGE_RATES_FAIL = "GET_EXCHANGE_RATES_FAIL";

export const ACCESS_KEY = '63d2ba6c2facc01aa57379fdc96acadf';
export const SOURCE = 'USD';